version: '3'

services:
  mysql-db-test:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - '3306:3306'
    volumes:
      - mysql_test_data:/var/lib/mysql

  api-test:
    command: >
      sh -c "npm run test:e2e"
    depends_on:
      - mysql-db-test
    ports:
      - ${PORT}:${PORT}
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_HOST: mysql-db-test
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      PORT: ${PORT}
    restart: unless-stopped

volumes:
  mysql_test_data:
